### ISSUE TITLE
msys64

### ISSUE THREAD

**Issue by sec13b** [Processus-Thief/CobaltStrikeBypassDefender#1]
on my msys64 is not recognized x86_64-w64-mingw32-c++.exe

![image](https://github.com/Processus-Thief/CobaltStrikeBypassDefender/assets/123419537/f9960cf7-6f80-4b4e-8127-585791fd2b07)
![image](https://github.com/Processus-Thief/CobaltStrikeBypassDefender/assets/123419537/1b01c215-17e3-4358-bbde-d0f17f1e0f41)

**Comment by ProcessusT** [comment]
You need to install the gcc compiler for msys :

pacman -Syu
pacman -S base-devel gcc vim cmake

check at the end of documentation : https://www.msys2.org/#installation
